### PR TITLE
Update to v1.5.1

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Comment by jacobgkau** [comment]
I'm getting an error trying to install this on 20.04 or 21.04:
```
system76@pop-os:~$ sudo apt install nvidia-container-toolkit
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-container-toolkit : Depends: libnvidia-container-tools (>= 1.4.0) but 1.3.0-1pop1~1601490873~20.04~cb62a8d is to be installed
E: Unable to correct problems, you have held broken packages.
```

Looks like https://github.com/pop-os/libnvidia-container also needs to be updated (it looks like there's an `upstream-v1.4.0` branch that didn't build for 21.04 last time it was updated.)

**Comment by mmstick** [comment]
We did get 1.4.0 released 15 days ago, but I see that it is not in our PPA

**Comment by mmstick** [comment]
@jacobgkau Staging now has libnvidia-container 1.4.0

**Review by jacobgkau — APPROVED** [review]
`libnvidia-container1` is in staging but not proposed. With staging added, this update works on 21.04 and 20.04.

**Pull request merged**
